name: Cargo

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  # By default, RUSTFLAGS with “-D warnings” turns “asm_const” warnings into errors.
  RUSTFLAGS:

jobs:
  fmt:
    name: Rustfmt all packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  build:
    name: Build examples
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: thumbv6m-none-eabi
          toolchain: nightly
      - name: Build under default features
        run: cargo build --examples --target thumbv6m-none-eabi
      # - name: Build under no embassy feature
      #   run: cargo build --examples --no-default-features --target thumbv6m-none-eabi
